= Developing with Python

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Akka Serverless Python SDK offers an idiomatic Python language SDK for writing APIs and Services that will run in the Akka Serverless Platform-as-a-Service product. This page describes prerequisites for Python development and basic requirements for a development project. It is recommended that you check out the https://developer.lightbend.com/docs/akka-serverless[Akka Serverless documentation] site for introduction to the product itself, including the concepts.

NOTE: Lightbend provides Tier 3 support for the Python SDK. See https://developer.lightbend.com/docs/akka-serverless/faq/index.html#_what_languages_are_supported[an explanation of support tiers] for more information. Further development will need to happen to take the Python support to Tier 2. Use of this SDK in a production environment is not recommended. Please visit https://github.com/jpollock/akkaserverless-python-sdk/discussions to add ideas or ask questions specific to the Python SDK.

Your development project needs to include the Akka Serverless Python SDK. You define API components using https://developers.google.com/protocol-buffers[protobuf] and use `protoc` to compile them. Finally, you implement business logic for service components.

//To save the work of starting from scratch, the Python xref:kickstart.adoc[code generation tool] creates a project, complete with descriptors and implementations. Or, you can start from one of our https://developer.lightbend.com/docs/akka-serverless/tutorial/index.html[example applications].

== Prerequisites

The following are required to develop Akka Serverless services in Python:

Python:: Akka Serverless requires at least Python {minimum_python_version}. Download and install Python https://www.python.org/[here {tab-icon}, window="new"].

Docker:: Akka Serverless requires https://docs.docker.com/get-docker/[Docker {tab-icon}, window="new"] {minimum_docker_version} for building your service images. Most popular build tools have plugins that assist in building Docker images.

== Development project requirements

The following examples show how to install the SDK for use in your Python code.

//NOTE: The code generation tools do more than just provide a starter project, after you modify a `.proto` file, they will generate code stubs for the elements you changed or added.

If you are starting from scratch, you will need to add configuration and code to:

* <<_add_sdk_libraries>>
* <<_define_grpc_descriptors_and_compile>>
* <<_create_and_start_the_grpc_server>>

== Add SDK libraries

Once you have the prerequisites, you need to add the `@lightbend/akkaserverless-python-sdk` package to your service development project, which can be done by running:

[source,sh,subs="attributes+"]
----
pip install akkaserverless 
----

You can also use the `requirements.txt` file found in the samples and starter projects.

[source,sh,subs="attributes+"]
----
pip install -r requirements.txt
----

To create a basic service, you need to include the `akkaserverless` package dependencies in your project, define gRPC descriptors in `.proto` files and reference them in your project, compile the `.proto` files, and have logic to start the gRPC server in your source code.

=== Define gRPC descriptors and compile

Descriptors for gRPC are defined in `protobuf` files. You can place `protobuf` files in your project wherever you like, for example, in the root directory, or in a directory named `protos`. For the Python SDK, right now, it is recommended to keep in the root directory. See xref:proto.adoc[] for more details.

=== Precompile the protobuf descriptor set

The gRPC descriptor is serialized to binary using the Protobuf https://developers.google.com/protocol-buffers/docs/techniques#self-description[`FileDescriptorSet` message type]. In order to use protobuf in the Python SDK you need to generate the Python stubs. This can be done by using the `compile.sh` script, which is located in the `bin` directory of the SDK repository itself; when installing the SDK, if you do so within a virtual environtment (using https://docs.python.org/3/library/venv.html or https://github.com/pyenv/pyenv-virtualenv), the script will be located in the path of your terminal and you should be able to type `compile.sh` directly, from the root of the project.

=== Create and start the gRPC server

To create a server, you can use the link:{attachmentsdir}/api/module-akkaserverless.AkkaServerless.html[`AkkaServerless`{tab-icon}, window="new"] class, add one or more entities to it, and then invoke link:{attachmentsdir}/api/module-akkaserverless.AkkaServerless.html#start[`start`{tab-icon}, window="new"], like so:

[source,python,indent=0]
----
include::example$python-customer-registry/index.py[tags=start]
----

//For all options available on the `AkkaServerless` class, see link:{attachmentsdir}++/api/module-akkaserverless.AkkaServerless.html#~options++[`AkkaServerless~options`{tab-icon}, window="new"].

== What's next

This section includes information on the following topics:

* xref:python:proto.adoc[]
* xref:eventsourced.adoc[Event Sourced Entities]
* xref:python:value-entity.adoc[]
* xref:python:views.adoc[]
* xref:forwarding.adoc[Forwarding and effects]
* xref:python:topic-eventing.adoc[]
* xref:serialization.adoc[Serialization]
//* link:{attachmentsdir}/api/index.html[Python API docs{tab-icon}, window="new"]

////

ifdef::review[REVIEWERS: the following was removed from a page on replicated entities for if and when we support them in the future and references to Chat were removed because it isn't working.]

= Replicated entities

include::ROOT:partial$include.adoc[]

This page documents how to implement Replicated Entities in Javascript. For information on what  Replicated Entities are, please read how to https://developer.lightbend.com/docs/akka-serverless/designing/state-model.html[choose a state model] and the general xref:developing:crdts.adoc[Replicated Entity] information first.



== Init default value of Replicated Entity

We can init the state like the following code
[source,python,indent=0]
----
entity.defaultValue = () => new replicatedData.ReplicatedSet();
----


== Handling commands

By default, the name of the command that the method handles will be the name of the method with the first letter capitalized. So, a method called `getFriends` will handle a gRPC service call command named `GetFriends`.

The command handler also can take the gRPC service call input type as a parameter to receive the command message. This is optional, sometimes it's not needed.

The return type of the command handler must be the output type for the gRPC service call, this will be sent as the reply.

The following shows the implementation of the command handlers. In the following example, the command handlers `add` and `remove` update the state in Replicated Entity:

[source,python,indent=0]
----
function add(friend, ctx) {
  ctx.state.add(friend.friend);
  return {};
}

function remove(friend, ctx) {
  ctx.state.delete(friend.friend);
  return {};
}

function getFriends(user, ctx) {
  console.log("getFriends for user: "+ user, {
    friends: Array.from(ctx.state)
  });
  return {
    friends: Array.from(ctx.state)
  };
}

entity.commandHandlers = {
  Add: add,
  Remove: remove,
  GetFriends: getFriends
};
----

== Streamed command handlers

Replicated Entities support streaming over gRPC. Streamed commands can be used to receive and publish updates to the state. The detail is in link:{attachmentsdir}/api/module-akkaserverless.replicatedentity.ReplicatedEntityCommandContext.html[`ReplicatedEntityCommandContext`{tab-icon}, window="new"].



== Referral Docs
////
